### ISSUE TITLE
scrollbar scroll isn't possible as it triggers dragging

### ISSUE THREAD

**Issue by julmot** [txusko/PostItAll#10]
Scrolling this content with the scrollbar will trigger dragging action:
![drag](https://cloud.githubusercontent.com/assets/8310677/12911102/3951ad06-cf10-11e5-9af1-cf5417b2e705.png)

**Comment by txusko** [comment]
I have disabled the "draggable" feature when the note flips to any of the "back" panels, so now should works fine.
https://github.com/txusko/PostItAll/commit/f29c06129f98ef9f4e5e9e319f001ebccee192a6

Thanks!
Javi Filella

**Comment by julmot** [comment]
@txusko I don't think disabling the dragging completely would be necessary. Just check `event.target` against the div with all the informations inside. If they are equal, dragging should not be triggered.
