### ISSUE TITLE
responsive behaviour of "Attach note to an element"

### ISSUE THREAD

**Issue by julmot** [txusko/PostItAll#11]
If you attach a note to an element it will keep sticky to it. However, when resizing your browser it should act responsive. Currently when resizing to a smaller viewport than the original it will become hidden. It would be great to have the possibility to influence this behaviour, like:
```javascript
breakpoints:  {
    '1024'`: {
        'stickyEdge': 'left'
    },
    '768': {
        'stickyEdge': 'bottom'
    }
}
```
which would show the note on the bottom site on > 768px viewports and on the left site on > 1024px viewports.
The alternative would be that the plugin detects if a note is hidden and trys to find an edge where it isn't.

**Comment by txusko** [comment]
I finally take the alternative option, so when the note is in a hidden position, it will be moved "inside" the attached element with the arrow pointing in the opposite direction (from inside to outside). I hope it helps.

https://github.com/txusko/PostItAll/pull/22

Best regards
Javi Filella
