### ISSUE TITLE
What is this noteController.php about?

### ISSUE THREAD

**Issue by julmot** [txusko/PostItAll#12]
When installing the backage with bower this file will be shipped within the packages `dist` folder. However, I don't see a documentation about it.

**Comment by txusko** [comment]
It's a php controller example for the storage backend under PHP. 
It's part of an example to store the saved notes in a mysql database. 
http://postitall.txusko.com/examples/externalStorage.html

I will review the bower installation to avoid the inclusion of this file in the futures releases.

Best regards
Javi Filella

**Comment by txusko** [comment]
https://github.com/txusko/PostItAll/commit/ca990aed13d6624fc61161934ac6c129836f826f
https://github.com/txusko/PostItAll/commit/f5b525dc9ba12c69e1247a38edc2f87f99402964

**Comment by accorinti** [comment]
Could you please write a very short description, how to use noteController?
On the page http://postitall.txusko.com/examples/externalStorage.html
if I check the source I don't see any PHP...
Just shortly how to use this php-class please :-)
