### ISSUE TITLE
Add hint about browser compatibility

### ISSUE THREAD

**Issue by julmot** [txusko/PostItAll#13]
There isn't a documentation about the browser compatibility. What I expect:
- From which browser and version is the plugin compatible?
- Is the plugin able to save notes when using it from a webpage with the `file:///`-protocol?

**Comment by txusko** [comment]
Added browser compatibility in README.md. 
https://github.com/txusko/PostItAll/commit/fce6082a61d58797a6e9b18fb2a53f5ef2036500

It seems that don't work on Opera, and I have don't tested yet on Explorer and Edge.
