### ISSUE TITLE
Feature request: Ability to add metadata to a note

### ISSUE THREAD

**Issue by julmot** [txusko/PostItAll#14]
It would be great to have the ability to add metadata to a note (predefined structure).
Something like that:
```javascript
meta: {
    'title': {
        'type': 'input',
        'maxlength': '100'
    },
    'category': {
        'type': 'input'
    }
}
```
This would add further abilities, like filtering based on metadata.

**Comment by txusko** [comment]
I don't understand the aim of this feature. 

Do you want to add "data" attributes in the DOM final object? For example:
<div data-title="title" data-category="stuff" ... >Note</div>

**Comment by julmot** [comment]
No, not data attributes. In the note popup you can enter text. Now, in separate text inputs (defined in a structure above) you could add additional meta informations. Do you know what I mean?

**Comment by txusko** [comment]
Yeah! I didn't understand well at first. 
I like the idea, and I will try to add it in future releases.

Thanks again Julian!

**Comment by txusko** [comment]
Hi again Julian,

I have created a new branch with this feature:
https://github.com/txusko/PostItAll/tree/PostItAll-1.0.8-MetaData

You can try it here:
http://postitall.txusko.com/tmp/localStorage.html
(create a note and click on the "info icon" on the left-buttom corner of the note. You will see 2 tabs, the meta-data is in the second one)

Is this what you expected?

Best regards
Javi Filella

**Comment by julmot** [comment]
Thanks Javi, this is what I was looking for.

**Comment by txusko** [comment]
https://github.com/txusko/PostItAll/pull/26

**Comment by julmot** [comment]
@txusko Is it possible to assign a specific meta information to a new note? For example if the user would click on a specific button "Personal" I would know that he would like to add a note for this category. So I could set this information for him.
