### ISSUE TITLE
How to get all notes?

### ISSUE THREAD

**Issue by julmot** [txusko/PostItAll#15]
When doing something for each node I would need a method to get all notes, like:
```javascript
$.PostItAll.getNotes();
```
It should return all notes and all metadata about it and a DOM reference.

**Comment by txusko** [comment]
https://github.com/txusko/PostItAll/commit/89a2a37a625e7ce998fcd6eb9f72caeb91c92b25

I will add the documentation for this new method with the splited gh-pages 

Best regards
Javi Filella
