### ISSUE TITLE
Feature request: Share notes

### ISSUE THREAD

**Issue by julmot** [txusko/PostItAll#16]
A quite cool thing would be to share notes between people. In my opinion there are only two ways of doing this:
- Implement a note export as JSON. Then the user could copy the code, save it in a file and send it to a friend. The friend could then import the file to see all the notes from his friend.
- Setup an online service. The application would send all notes to it and it would save it in a database. Further it would generate a unique hash that is related to the notes. A user could then send this hash to a friend which could enter it in the application to retrieve the notes from his friend.

I personally prefer the first way as this is
- less complex
- brings no safety problems with it
- makes no maintenance necessary
- brings up no downtime issues
- doesn't need an online connection
- would be easy to implement as an automatically file export with the "Save as" dialog in hybrid apps

@txusko What do you think?

**Comment by txusko** [comment]
It's a very good idea. Months ago I was thinking the best way to achieve the goal, but all solutions go through an online service and a user registration. 
I think the json import/export will not be difficult to implement and fits a first approach to make the plugin more social.

Just out of curiosity, I'm currenly developing a new feature to share the note in the main social networks (twitter, fb & g+) :smile: 
https://github.com/txusko/PostItAll/tree/PostItAll-share-note

**Comment by julmot** [comment]
I agree. Do you plan to implement this?
It would not be so difficult like an online service. However, it will be a challenge though. Necessary to implement would be:
- export the note itself as JSON
- export the position or the attached element (unique selector creation would be necessary)
- reimport the JSON to restore all things

**Comment by txusko** [comment]
Sure, I don't know when but I will try to implement it. 
If you have a clean picture of how and what to do, and you want to give me a hand, I will be eternally greatful :smile:

**Comment by txusko** [comment]
Hi again Julian, what about something like this?

http://postitall.txusko.com/tmp/localStorage.html
https://github.com/txusko/PostItAll/tree/PostItAll-1.0.9-ImportExport

**Comment by julmot** [comment]
Hi Javi,
look great on first glance. I will review this tomorrow, as I don't have the time at the moment.
Cheers

**Comment by txusko** [comment]
Don't worry, there's no rush. :smiley:

**Comment by julmot** [comment]
Thanks Javi. I appreciate your work and effort to build this feature.
For me the JSON looks pretty good and export/import worked in your example. I'm curious how this behaves when exporting/importing notes attached to elements or in a real application. I think I will have some further issues with this, but for the moment we can close this as successfully implemented.

**Comment by txusko** [comment]
Merged : #32 
Thanks again Julian
