### ISSUE TITLE
Split repository into gh-pages, chrome extension and jquery plugin

### ISSUE THREAD

**Issue by julmot** [txusko/PostItAll#18]
To avoid confusion I think it would be the best to split this repository into three parts: gh-pages (for the documentation), chrome extension and jquery plugin.

**Comment by txusko** [comment]
Sorry but I'm not an advanced user in github ... when you say "split this repository" you means to create 3 different repositories? or github has any tool to split a created repository into others? Do you have any example or reference page? 

Anyway, here is the chrome-extension repository:
https://github.com/txusko/PostItAll-ChromeExtension

**Comment by julmot** [comment]
Thanks for letting me know that you already have a separate repository for the Chrome extension. That is good!

In Github it is common to create a branch called "gh-pages" and host the website about the project there. You can simply create this new branch, copy all files related to the website to it and only let the actual related plugin files in the master branch. This way you don't host the website for yourself, GitHub will take care of this. See [this page for a documentation about gh-pages](https://pages.github.com/).

So you would have to create a `gh-pages` branch for the Chrome extension repository and for the jQuery plugin repository. Then your landingpage isn't needed anymore.

**Comment by txusko** [comment]
I shall certainly be taking that into account in the next release.

Thank you so much Julian.
Javi Filella

**Comment by txusko** [comment]
Splitted repository in "gh-pages" for the website and "master" for the plugin.

Regards
Javi Filella
