### ISSUE TITLE
Update documentation to show example of defining a single global option

### ISSUE THREAD

**Issue by julmot** [txusko/PostItAll#27]
For example

```javascript
$.fn.postitall.globals = {
    showInfo: false
};
```
will fail, as it will override not just `showInfo`, but all options. So there is a hint necessary that shows how to set a single option. It could look like:
```javascript
$.fn.postitall.globals.showInfo = false;
```

**Comment by txusko** [comment]
I have implemented two global methods to change & restore configuration:
http://postitall.txusko.com/plugin.html#doc_changeglobalconfig

```
$.PostItAll.changeConfig('global', {
    showInfo : false
});
```

Anyway, you can change the configuration like you do in your second example, so I will add it in the documentation coming soon. :+1:

**Comment by txusko** [comment]
I am trying to split the documentation into gh-pages. Until then I will not update the documentation with the new features & corrections. Sorry.

**Comment by julmot** [comment]
No problem. If there exists a way to override the setting it's not necessary. I didn't noticed that.
