### ISSUE TITLE
"attachedTo" should support jQuery elements, not just selectors

### ISSUE THREAD

**Issue by julmot** [txusko/PostItAll#28]
The documentation does not provide information about what kind of value it expects:
![doc](https://cloud.githubusercontent.com/assets/8310677/13738294/4248d046-e9c4-11e5-9af2-bd7fde26088a.png)
However, it seems that it supports only selectors. In my opinion passing a jQuery DOM element should be possible too.

**Comment by txusko** [comment]
https://github.com/txusko/PostItAll/commit/42f40f1b32476b6592af10121e729b001a83529f
