### ISSUE TITLE
Attaching a note is buggy

### ISSUE THREAD

**Issue by julmot** [txusko/PostItAll#29]
When attaching a note to an element, it looks bugy. A scrollbar will appear and the note will be overflown:

![nothingappears](https://cloud.githubusercontent.com/assets/8310677/13738376/d6b7b472-e9c4-11e5-917e-39901f63d416.png)

Code to reproduce:
[noteTest.zip](https://github.com/txusko/PostItAll/files/171555/noteTest.zip)

Seems like a refactoring of this feature is necessary.

**Comment by julmot** [comment]
There's a project that realizes this and that will be a dependency for Bootstrap 4: http://tether.io/

Might be worth thinking about attaching nodes with this too.

**Comment by txusko** [comment]
I didn't know that library, I will take a look ...
Thanks Julian

**Comment by txusko** [comment]
Hey Julian, I was doing improvements in the attachedTo method. I think now the notes should be attached to the objects always in the visible browser area without scrollsbars.
https://github.com/txusko/PostItAll/commit/655bc81fe4696857ac7905972587caded06873e4

Anyway when I have time I will try to integrate the tether.io plugin

Best regards!
Javi Filella
