### ISSUE TITLE
Can't save content with spaces

### ISSUE THREAD

**Issue by Ciatronical** [txusko/PostItAll#3]
When save content with spaces via ajax, remove all after space.
Bugfix is in patchfile. Thanks for postitall...
[0001-Bugfix-Can-t-save-spaces.patch.zip](https://github.com/txusko/PostItAll/files/97787/0001-Bugfix-Can-t-save-spaces.patch.zip)

**Comment by txusko** [comment]
Hi @Ciatronical 

You are right. I've just applied the path.
https://github.com/txusko/PostItAll/commit/ac9d3907bf80ae7879eb22c70bdbbe84c4271f33

Thank you very much!
