### ISSUE TITLE
Why is it necessary to track the OS name?

### ISSUE THREAD

**Issue by julmot** [txusko/PostItAll#31]
Notes contain informations about the OS, the domain and the page. Why are those informations necessary to track?

**Comment by txusko** [comment]
It's only information about the note environment when the note was created. 

Internally, the domain & page attributes are used to filter notes with the chrome extension. Also in Chrome extension, the OS info could be helpful if you have synchronized browsers in different OS machines (work, home) and want to know from which machine the note was created.

You can always disable the info tab:
$.fn.postitall.globals.showInfo = false;

**Comment by julmot** [comment]
Will the info tab contain any other informations beside to the named ones, like meta informations or something else that would be disabled too?

**Comment by txusko** [comment]
No, it shows only the note information. The meta-data is showed when the "showMeta" param is set to true. The two tabs (info & meta) are within the same icon (info icon).

**Comment by julmot** [comment]
Alright, then disabling it seems to be ok.
