### ISSUE TITLE
npm release update

### ISSUE THREAD

**Issue by julmot** [txusko/PostItAll#33]
Hey Javi,

I renounce the use of `npm` where I can. However, I've just had a look at your plugin over there and it seems to be quite outdated ([link](https://www.npmjs.com/package/postitall). You may publish new releases there.

Cheers

**Comment by txusko** [comment]
I don't use npm so much, and I'm a little bit lost. I have just published the tatest release in npm. I think I have do it well, but if you can check it out I will be grateful. :-)
