### ISSUE TITLE
Fix moving

### ISSUE THREAD

**Issue by ToriomLab** [txusko/PostItAll#36]
I want the sticky not movement at all page 

just move it inside the box for example 600*600 from my page 

How can I do that?

**Comment by txusko** [comment]
Hi @ToriomLab 

I'm sorry but it's not possible. Anyway, I think you can try to achieve the goal by modifying the jquery draggable call (if you use the jquery UI) of the plugin: https://github.com/txusko/PostItAll/blob/master/dist/jquery.postitall.js#L2809
Example: https://jqueryui.com/draggable/#constrain-movement

I hope it helps ... Regards!
Javi Filella
