### ISSUE TITLE
database solution

### ISSUE THREAD

**Issue by neo125874** [txusko/PostItAll#38]
hello, did you have any example for storing & loading from the db solution?
maybe the api to change the local storage?
or did i miss anything by the document?
thanks.

**Comment by txusko** [comment]
Hi @neo125874 

Yes, I have implemented an example in the plugin "gh-pages". Here are the links:

Front-end: 
https://github.com/txusko/PostItAll/blob/gh-pages/examples/externalStorage.html

Rewritten plugin storage example (client): 
https://github.com/txusko/PostItAll/blob/gh-pages/dist/jquery.postitall.ajax.js

Note controller example (server):
https://github.com/txusko/PostItAll/blob/gh-pages/dist/noteController.php

Anyway, it's only a proof-concept and I think you'll need to rewrite the client/server communication to fit your needs.

I hope it helps ... Regards!
Javi Filella
