### ISSUE TITLE
Interaction of Trumbowyg in the YunoHost package.

### ISSUE THREAD

**Issue by anmol26s** [txusko/PostItAll#39]
Hi
Can you help in integrating Trumbowyg in the [YunoHost Chticynotes package](https://github.com/YunoHost-Apps/chtickynotes_ynh). I tried adding the Trumbowyg css and js in the [index file](https://github.com/YunoHost-Apps/chtickynotes_ynh/blob/master/sources/index.html) ,but it messed up the notes. The real maintainer of the package is not maintaining it anymore.

Thanks

**Comment by txusko** [comment]
Hi @anmol26s, I'm sorry but I'm really busy from the last year and I almost not maintaining this plugin too. Therefore, I will not be able to lend you my help.
Best regards
Javi

**Comment by anmol26s** [comment]
Np, Thanks for doing this app.
