### ISSUE TITLE
Compatibility with JQuery 3.x

### ISSUE THREAD

**Issue by pgodiani** [txusko/PostItAll#42]
Bower package requires Jquery from branch 2.x.
Any plan to make the plugin compatible with more recent Jquery 3. ?

**Comment by txusko** [comment]
Sure! I think that the plugin works with jQuery 3.0 but I have to test it a little bit more. I tell you something asap.
Kind regards

**Comment by txusko** [comment]
Jquery version upgraded to version ~3.5.0
