### ISSUE TITLE
Savable not working

### ISSUE THREAD

**Issue by spacetraveller** [txusko/PostItAll#44]
For some reason, the post it notes are not saving to local storage. If "savable: true" is set, then whenever attempt to create a new sticky, nothing happens and there is no feedback to the console with an error.

```
function createSticky(evt) {
            $.PostItAll.new({
                content : "",
                width: 260,
                height: 260,
                posX: evt.pageX,
                posY: evt.pageY + 20,
                features: {
                    savable: true,
                    resizable: true
                }
            });

        }
```

If you set "savable: false", then the sticky appears.

**Comment by txusko** [comment]
Your code seems to be ok and works fine. I've just checked and notes appear. 
Maybe you forget to load the notes when the page it's loaded? `$.PostItAll.load();`.
http://localhost/~txusko/PostItAll/plugin.html#doc_save

This is the code I tested:
```
<script>
      function createSticky(evt) {
          $.PostItAll.new({
              content : "",
              width: 260,
              height: 260,
              posX: evt.pageX,
              posY: evt.pageY + 20,
              features: {
                  savable: true,
                  resizable: true
              }
          });

      }
      $(document).ready(function() {
        $.PostItAll.load();
        $('#idNew').click(function(e) {
            createSticky(e);
            e.preventDefault();
        });
      });
</script>
```

Or maybe it's something wrong with your configuration or your environement? You can try to change savable global configuration:
```
$.fn.postitall.globals.savable = true;
```
