### ISSUE TITLE
Filter doesnt't work properly

### ISSUE THREAD

**Issue by accorinti** [txusko/PostItAll#46]
Hello guys, awesome work first of all!

I use PostItAll on my site, but I have 1 page that shows the participants to our courses, we use the same page for all courses, we just attach to the page address a course ID number to show the different courses, like
www.mysite.com/my_students.php?courseID=5
Now, I need the post-its to be course relevant, I mean, I have different post-its for different courses.

I configured the global option "Filter" to "all" but I still get ALL the post-its of ALL courses...
filter: 'all',     //Options: domain, page, all
I also tryed with 'page' and 'domain' same result.

I tryed adding the courseID number to the prefix
prefix: '#PIApostit_<?php echo $courseID ."_"; ?>',  // Id note prefix
but I still get ALL the post-its of ALL courses...

May be you can help me with an idea on how to generate the post-it and load them according to different courses.

I guess this feature will be appreciated from a lot of people.

Thanks :-)

**Comment by txusko** [comment]
Hi accorinti, I'm so sorry but I think you will need to create your custom endpoint for your notes (I noticed you use php on the backend), and cover these restrictions on the server side. The JavaScript endpoint developed within this plugin do not restrict anything apart from the domain.

Regards,
Javi Filella
