### ISSUE TITLE
Restrict note in a specific div

### ISSUE THREAD

**Issue by mickeychu** [txusko/PostItAll#49]
Hi, is there any way to restrict the note inside a certain div? 

The idea is that user can drag&drop freely inside this div but he can not move this note outside the div.

Thank you for this great plugin!!!

Mickey

**Comment by txusko** [comment]
Hi Mickey, the idea wasn't to restrict the note to any certain `div` so the initial answer is no. 
Anyway, maybe you could take advantage of `#the_notes` div, I mean, the plugin when it initializes, creates a new div inside the body
https://github.com/txusko/PostItAll/blob/a026607d5a3393bcf0f7ae7822f0f388f3defdac/dist/jquery.postitall.js#L427-L429
And all the notes are created inside this div:
https://github.com/txusko/PostItAll/blob/a026607d5a3393bcf0f7ae7822f0f388f3defdac/dist/jquery.postitall.js#L677
Maybe with a bit of css you can restrict how the notes behave inside this div.

Hope it helps, 
Javi Filella
