### ISSUE TITLE
Can't create new note when savable true

### ISSUE THREAD

**Issue by Ciatronical** [txusko/PostItAll#5]
It's a sporadic error. I think the following git patch corrects the error.
[bugfix.zip](https://github.com/txusko/PostItAll/files/117169/bugfix.zip)

**Comment by txusko** [comment]
Hi Ronny, I have fixed the issue with a mixed solution :D
https://github.com/txusko/PostItAll/commit/c29270a4121c83f9e71626b6d6d5d3d0b5a4b61d

Best Regards
Javi Filella
