### ISSUE TITLE
outsource note styles to css

### ISSUE THREAD

**Issue by julmot** [txusko/PostItAll#9]
The documentation shows how to style a note:

``` javascript
    //Config note style
    style : {
        tresd           : true,                 //General style in 3d format
        backgroundcolor : '#FFFA3C',            //Background color in new postits when randomColor = false
        textcolor       : '#333333',            //Text color
        textshadow      : true,                 //Shadow in the text
        fontfamily      : 'verdana',            //Default font
        fontsize        : 'small',              //Default font size
        arrow           : 'none',               //Default arrow : none, top, right, bottom, left
    }
```

However, this seems to be not really modern. If you want to style your note you will come to a point, where things like that aren't enough (e.g. you could need a box-shadow).
The way a note looks should be defined in a CSS class instead of a JS configuration.

**Comment by txusko** [comment]
But these variables can be configured on the fly from the back-panel configuration. Some are embebed in the style attribute of the element, and others are adding or removing css classes, for example the "3d" style, the textshadow, etc. Do you have any idea about it?

**Comment by julmot** [comment]
Basically you should not define CSS in the plugin. Instead, just add CSS classes to an element. That allows designers to style notes with pure CSS, they just need to know what class will be added to what element.
Take [this project](https://github.com/julmot/jmHighlight) as an example. It highlights keywords. Now in your way this plugin would just offer to change e.g. the color with an option. But this will mix up styling and scripting, which is bad. Also it makes it harder to maintain and integration can be difficult. On top, as I already said, when designers want to add CSS that your plugin doesn't provide, they would have to adjust the plugin. This is why this project simply allows to pass a class name. Then styling is a completely separate thing and nothing is mixed together.

**Comment by julmot** [comment]
For me, this is the most fundamental issue. Customers expect a feature to look like their StyleGuide and styling a note with the current implementation seems to be expensive and cumbersome, functions and styles should be splitted (JS, CSS) as long as possible.

**Comment by txusko** [comment]
Sorry, I was working to outsource the note style to a css class. Still much work to be done, but when you can, If you take a look at this branch and tell me if I'm in the right direction.

https://github.com/txusko/PostItAll/tree/Outsource-note-styles-to-css
Examples in https://github.com/txusko/PostItAll/blob/Outsource-note-styles-to-css/examples/cssnote.html

**Comment by julmot** [comment]
@txusko Thank you for your work! I've seen there's a great progress. Unfortunately I'm currently not able to review the things due to lack of time.

**Comment by txusko** [comment]
Don't worry @julmot I'll continue working and try to do my best. 👍

**Comment by txusko** [comment]
Branch d6a7a82999921e65886b33d8c77c61db78ddcdec merged & new version published.
Regards!
